fix(ci): Harfbuzz build failure on master/nightly (#2290)
__Issue:__ The `master` (nightly) builds were failing, with this error:

```
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @revery/esy-harfbuzz@2.6.8000

    # esy-build-package: pwd: C:\Users\VssAdministrator\.esy\3\b\revery__s__esy_harfbuzz-2.6.8000-2c0b225d

    # esy-build-package: running: "./esy/prep.sh"

    # esy-build-package: running: "bash" "-c" "./esy/configure-windows.sh"

    Install: /cygdrive/c/Users/VssAdministrator/.esy/3______________________________________________________/s/revery__s__esy_harfbuzz-2.6.8000-2c0b225d
    error: command failed: "bash" "-c" "./esy/configure-windows.sh" (exited with 127)

    esy-build-package: exiting with errors above...

    
  building @revery/esy-harfbuzz@2.6.8000
esy: exiting due to errors above
```

__Defect:__ There's an issue with the latest `cmake` install on Windows - it's no longer installing correctly in a way that provides the `cmake` executable.

__Fix:__ `cmake` was removed as a dependency for harfbuzz and replaced with a `./configure` script: https://github.com/revery-ui/esy-harfbuzz/commit/380833bb511ace7b700825fbbe51023ef7ffb6fb

This picks up that fix for Onivim